# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hwui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from View.PaintBoard import PaintBoard

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.epochEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.epochEdit.setObjectName("epochEdit")
        self.horizontalLayout_2.addWidget(self.epochEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.trainButton.setFont(font)
        self.trainButton.setObjectName("trainButton")
        self.verticalLayout.addWidget(self.trainButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(5)
        self.line_2.setMidLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.outputLayout = QtWidgets.QFormLayout()
        self.outputLayout.setObjectName("outputLayout")
        self.Label0 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label0.setFont(font)
        self.Label0.setObjectName("Label0")
        self.outputLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label0)
        self.LineEdit0 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit0.setFont(font)
        self.LineEdit0.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit0.setReadOnly(True)
        self.LineEdit0.setObjectName("LineEdit0")
        self.outputLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit0)
        self.Label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label1.setFont(font)
        self.Label1.setObjectName("Label1")
        self.outputLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label1)
        self.LineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit1.setFont(font)
        self.LineEdit1.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit1.setReadOnly(True)
        self.LineEdit1.setObjectName("LineEdit1")
        self.outputLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit1)
        self.Label2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label2.setFont(font)
        self.Label2.setObjectName("Label2")
        self.outputLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label2)
        self.LineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit2.setFont(font)
        self.LineEdit2.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit2.setReadOnly(True)
        self.LineEdit2.setObjectName("LineEdit2")
        self.outputLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit2)
        self.Label3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label3.setFont(font)
        self.Label3.setObjectName("Label3")
        self.outputLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label3)
        self.LineEdit3 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit3.setFont(font)
        self.LineEdit3.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit3.setReadOnly(True)
        self.LineEdit3.setObjectName("LineEdit3")
        self.outputLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit3)
        self.Label4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label4.setFont(font)
        self.Label4.setObjectName("Label4")
        self.outputLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label4)
        self.LineEdit4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit4.setFont(font)
        self.LineEdit4.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit4.setReadOnly(True)
        self.LineEdit4.setObjectName("LineEdit4")
        self.outputLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit4)
        self.Label5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label5.setFont(font)
        self.Label5.setObjectName("Label5")
        self.outputLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label5)
        self.LineEdit5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit5.setFont(font)
        self.LineEdit5.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit5.setReadOnly(True)
        self.LineEdit5.setObjectName("LineEdit5")
        self.outputLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit5)
        self.Label6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label6.setFont(font)
        self.Label6.setObjectName("Label6")
        self.outputLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label6)
        self.LineEdit6 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit6.setFont(font)
        self.LineEdit6.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit6.setReadOnly(True)
        self.LineEdit6.setObjectName("LineEdit6")
        self.outputLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LineEdit6)
        self.Label7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label7.setFont(font)
        self.Label7.setObjectName("Label7")
        self.outputLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label7)
        self.LineEdit7 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit7.setFont(font)
        self.LineEdit7.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit7.setReadOnly(True)
        self.LineEdit7.setObjectName("LineEdit7")
        self.outputLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LineEdit7)
        self.Label8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label8.setFont(font)
        self.Label8.setObjectName("Label8")
        self.outputLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Label8)
        self.LineEdit8 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit8.setFont(font)
        self.LineEdit8.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit8.setReadOnly(True)
        self.LineEdit8.setObjectName("LineEdit8")
        self.outputLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LineEdit8)
        self.Label9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.Label9.setFont(font)
        self.Label9.setObjectName("Label9")
        self.outputLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.Label9)
        self.LineEdit9 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.LineEdit9.setFont(font)
        self.LineEdit9.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit9.setReadOnly(True)
        self.LineEdit9.setObjectName("LineEdit9")
        self.outputLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LineEdit9)
        self.verticalLayout.addLayout(self.outputLayout)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout.addWidget(self.clearButton)
        
#        self.
        
        
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.paintBoard = PaintBoard()
        self.paintBoard.setObjectName("paintBoard")
        self.horizontalLayout.addWidget(self.paintBoard)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        
        
        self.progress_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.progress_label.setFont(font)
        self.progress_label.setMaximumWidth(400)
        self.progress_label.setAlignment(QtCore.Qt.AlignLeft)
        self.progress_label.setObjectName("progress_label")
        
        self.test_label = QtWidgets.QLabel(self.centralwidget)
        self.test_label.setFont(font)
        self.test_label.setObjectName("test_label")
        
        self.epoch_label = QtWidgets.QLabel(self.centralwidget)
        self.epoch_label.setFont(font)
        self.epoch_label.setObjectName("epoch_label")
        
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumWidth(300)
        self.progressBar.setMinimumWidth(200)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setAlignment(QtCore.Qt.AlignRight)
        
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
                
        
        w = QtWidgets.QWidget(self.centralwidget)
        w.setLayout(QtWidgets.QHBoxLayout())
        w.layout().addWidget(self.progress_label)
        w.layout().addWidget(self.test_label)
        w.layout().addItem(spacerItem)
        w.layout().addWidget(self.epoch_label)
        w.layout().addWidget(self.progressBar)

        self.statusBar.addWidget(w, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Weight"))
        self.label.setText(_translate("MainWindow", "epoch:"))
        self.trainButton.setText(_translate("MainWindow", "Train"))
        self.label_21.setText(_translate("MainWindow", "Possibility"))
        self.progress_label.setText(_translate("MainWindow", "Train: "))
        self.test_label.setText(_translate("MainWindow", "| Test: "))
        self.epoch_label.setText(_translate("MainWindow", "Epoch: "))
        self.Label0.setText(_translate("MainWindow", "0"))
        self.Label1.setText(_translate("MainWindow", "1"))
        self.Label2.setText(_translate("MainWindow", "2"))
        self.Label3.setText(_translate("MainWindow", "3"))
        self.Label4.setText(_translate("MainWindow", "4"))
        self.Label5.setText(_translate("MainWindow", "5"))
        self.Label6.setText(_translate("MainWindow", "6"))
        self.Label7.setText(_translate("MainWindow", "7"))
        self.Label8.setText(_translate("MainWindow", "8"))
        self.Label9.setText(_translate("MainWindow", "9"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))

                